import { Link } from "react-router-dom";

export default function Homepage() {
  return (
    <div className="homepage">
      <h1 className="homepage-title">Welcome to the 2024 Puppy Bowl!</h1>
      <Link className="homepage-link" to='/AllPlayers'>View Players</Link>
      <p className="homepage-p">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu mi bibendum neque egestas congue quisque. Morbi quis commodo odio aenean sed. Ornare suspendisse sed nisi lacus sed viverra tellus in. Turpis in eu mi bibendum. Tincidunt lobortis feugiat vivamus at augue eget arcu. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Tincidunt nunc pulvinar sapien et ligula. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Dictumst quisque sagittis purus sit amet volutpat consequat. Vitae aliquet nec ullamcorper sit amet risus. Ac felis donec et odio pellentesque diam volutpat commodo sed. Eleifend donec pretium vulputate sapien nec sagittis. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Consequat interdum varius sit amet mattis vulputate enim. Sem fringilla ut morbi tincidunt augue interdum velit euismod in. Amet consectetur adipiscing elit ut aliquam purus. Nibh mauris cursus mattis molestie. Adipiscing vitae proin sagittis nisl rhoncus mattis.</p>
      <p className="homepage-p">Urna duis convallis convallis tellus id interdum velit laoreet id. Morbi tristique senectus et netus et malesuada fames ac. Sed blandit libero volutpat sed cras ornare arcu dui. Faucibus in ornare quam viverra. Quam elementum pulvinar etiam non quam lacus. Eget felis eget nunc lobortis mattis aliquam faucibus. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Sagittis nisl rhoncus mattis rhoncus. Nec dui nunc mattis enim. Maecenas sed enim ut sem viverra aliquet. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Molestie at elementum eu facilisis sed. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Aliquam vestibulum morbi blandit cursus risus at ultrices. Pretium quam vulputate dignissim suspendisse in est ante in. Eget dolor morbi non arcu risus quis varius quam quisque. Scelerisque felis imperdiet proin fermentum leo. Consectetur adipiscing elit ut aliquam purus sit amet.</p>
      <p className="homepage-p">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu mi bibendum neque egestas congue quisque. Morbi quis commodo odio aenean sed. Ornare suspendisse sed nisi lacus sed viverra tellus in. Turpis in eu mi bibendum. Tincidunt lobortis feugiat vivamus at augue eget arcu. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Tincidunt nunc pulvinar sapien et ligula. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Dictumst quisque sagittis purus sit amet volutpat consequat. Vitae aliquet nec ullamcorper sit amet risus. Ac felis donec et odio pellentesque diam volutpat commodo sed. Eleifend donec pretium vulputate sapien nec sagittis. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Consequat interdum varius sit amet mattis vulputate enim. Sem fringilla ut morbi tincidunt augue interdum velit euismod in. Amet consectetur adipiscing elit ut aliquam purus. Nibh mauris cursus mattis molestie. Adipiscing vitae proin sagittis nisl rhoncus mattis.</p>
    </div>
  )
}